# Site settings
title: 和信治癌中心醫院 - Koo Foundation Sun Yat-Sen Cancer Center
email: rd.software@kfsyscc.org
description: KFSYSCC WebSite Download platform
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://kfsyscc.github.io # the base hostname & protocol for your site
twitter_username: 
github_username:  KFSYSCC
timezone: Asia/Taipei
exclude: [ "CNAME", "WebSite.sublime-project" ]
enforce_ssl: kfsyscc.github.io
officialURL: http://www.kfsyscc.org
homepage: http://www.kfsyscc.org/
sitemap: http://www.kfsyscc.org/sitemap/

google:
  analytics: UA-17823553-2
fb:
  app_id: 1627952920820693

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown

kramdown:
  input: GFM
